//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RFID.Order.Service.ConnectService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.rtp.com/", ConfigurationName="ConnectService.SupplierServiceSoap")]
    public interface SupplierServiceSoap {
        
        // CODEGEN: Generating message contract since element name xmlRequest from namespace http://www.rtp.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rtp.com/ProcessMessage", ReplyAction="*")]
        RFID.Order.Service.ConnectService.ProcessMessageResponse ProcessMessage(RFID.Order.Service.ConnectService.ProcessMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rtp.com/ProcessMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<RFID.Order.Service.ConnectService.ProcessMessageResponse> ProcessMessageAsync(RFID.Order.Service.ConnectService.ProcessMessageRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcessMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcessMessage", Namespace="http://www.rtp.com/", Order=0)]
        public RFID.Order.Service.ConnectService.ProcessMessageRequestBody Body;
        
        public ProcessMessageRequest() {
        }
        
        public ProcessMessageRequest(RFID.Order.Service.ConnectService.ProcessMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.rtp.com/")]
    public partial class ProcessMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xmlRequest;
        
        public ProcessMessageRequestBody() {
        }
        
        public ProcessMessageRequestBody(string xmlRequest) {
            this.xmlRequest = xmlRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcessMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcessMessageResponse", Namespace="http://www.rtp.com/", Order=0)]
        public RFID.Order.Service.ConnectService.ProcessMessageResponseBody Body;
        
        public ProcessMessageResponse() {
        }
        
        public ProcessMessageResponse(RFID.Order.Service.ConnectService.ProcessMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.rtp.com/")]
    public partial class ProcessMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ProcessMessageResult;
        
        public ProcessMessageResponseBody() {
        }
        
        public ProcessMessageResponseBody(string ProcessMessageResult) {
            this.ProcessMessageResult = ProcessMessageResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SupplierServiceSoapChannel : RFID.Order.Service.ConnectService.SupplierServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SupplierServiceSoapClient : System.ServiceModel.ClientBase<RFID.Order.Service.ConnectService.SupplierServiceSoap>, RFID.Order.Service.ConnectService.SupplierServiceSoap {
        
        public SupplierServiceSoapClient() {
        }
        
        public SupplierServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SupplierServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SupplierServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SupplierServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RFID.Order.Service.ConnectService.ProcessMessageResponse RFID.Order.Service.ConnectService.SupplierServiceSoap.ProcessMessage(RFID.Order.Service.ConnectService.ProcessMessageRequest request) {
            return base.Channel.ProcessMessage(request);
        }
        
        public string ProcessMessage(string xmlRequest) {
            RFID.Order.Service.ConnectService.ProcessMessageRequest inValue = new RFID.Order.Service.ConnectService.ProcessMessageRequest();
            inValue.Body = new RFID.Order.Service.ConnectService.ProcessMessageRequestBody();
            inValue.Body.xmlRequest = xmlRequest;
            RFID.Order.Service.ConnectService.ProcessMessageResponse retVal = ((RFID.Order.Service.ConnectService.SupplierServiceSoap)(this)).ProcessMessage(inValue);
            return retVal.Body.ProcessMessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RFID.Order.Service.ConnectService.ProcessMessageResponse> RFID.Order.Service.ConnectService.SupplierServiceSoap.ProcessMessageAsync(RFID.Order.Service.ConnectService.ProcessMessageRequest request) {
            return base.Channel.ProcessMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<RFID.Order.Service.ConnectService.ProcessMessageResponse> ProcessMessageAsync(string xmlRequest) {
            RFID.Order.Service.ConnectService.ProcessMessageRequest inValue = new RFID.Order.Service.ConnectService.ProcessMessageRequest();
            inValue.Body = new RFID.Order.Service.ConnectService.ProcessMessageRequestBody();
            inValue.Body.xmlRequest = xmlRequest;
            return ((RFID.Order.Service.ConnectService.SupplierServiceSoap)(this)).ProcessMessageAsync(inValue);
        }
    }
}
